# sudo -i 
# curl -L https://github.com/docker/compose/releases/download/1.5.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# weave launch-router --dns-domain="demo.stratio.com." --init-peer-count 1 && weave launch-proxy -H tcp://0.0.0.0:12375
# weave expose
# eval $(weave env)

zookeeper:
  image: qa.stratio.com:5000/stratio/zookeeper:3.4.6
  container_name: zookeeper
  ports:
    - "2181:2181"

waitzk:
  image: aanand/wait
  container_name: waitzk
  links:
      - zookeeper

kafka:
  image: qa.stratio.com:5000/kafka:0.8.1.1
  container_name: kafka
  ports:
    - "9092:9092"
  links:
    - waitzk
  environment:
    ZK_CONNECT: zookeeper.demo.stratio.com:2181

waitkafka:
  image: aanand/wait
  container_name: waitkafka
  links:
    - kafka

cassandra-lucene-index:
  image: stratio/cassandra-lucene-index:2.2.4.0
  container_name: cassandra
  ports: 
    - "9042:9042"
  environment:
    CLUSTER_NAME: DemoCluster
    MAX_HEAP: 256M
    MAX_NEW: 64M
    SEEDS: 127.0.0.1

waitcassandra:
  image: aanand/wait
  container_name: waitcassandra
  links:
    - cassandra-lucene-index

mongo:
  image: stratio/mongo:3.0.4
  container_name: mongo
  ports: 
    - "27017:27017"

waitmongo:
  image: aanand/wait
  container_name: waitmongo
  links:
    - mongo

elasticsearch:
  image: qa.stratio.com:5000/stratio/elasticsearch:1.7.1
  container_name: elasticsearch
  ports: 
    - "9300:9300"

waitelastic:
  image: aanand/wait
  container_name: waitelasticsearch
  links:
    - elasticsearch

decision:
  image: qa.stratio.com:5000/stratio/decision:1.0.0-RC1
  container_name: decision
  links:
    - waitkafka
    - waitcassandra
    - waitmongo
    - waitelastic
  environment:
    KAFKA_HOSTS: kafka.demo.stratio.com:9092
    ZOOKEEPER_HOSTS: zookeeper.demo.stratio.com:2181
    CASSANDRA_HOSTS: cassandra.demo.stratio.com
    MONGODB_HOSTS: mongo.demo.stratio.com:27017
    ES_HOSTS: elasticsearch.demo.stratio.com:9300
#   SOLR_HOSTS;
    CLUSTERING_ENABLED: "false"
    GROUP_ID: stratiogroup
#    CLUSTER_GROUPS: stratiogroup
#    DATATOPICS: stratiotopic
    FAILOVER_ENABLED: "true"

decision-shell:
  image: qa.stratio.com:5000/stratio/decision-shell:1.0.0-RC1
  container_name: shell
  links:
    - decision
  environment:
    KAFKA_HOSTS: kafka.demo.stratio.com:9092
    ZOOKEEPER_HOSTS: zookeeper.demo.stratio.com:2181

#eval $(weave env --restore)
